# Generated by Django 4.2.7 on 2023-11-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_remove_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
