# Generated by Django 4.2.7 on 2023-11-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedimage",
            name="original_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="original_images/"
            ),
        ),
    ]
